<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joshua TING">
<meta name="dcterms.date" content="2024-09-30">

<title>Navigating Geospatial Mines - Take-Home Exercise 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Navigating Geospatial Mines</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-On Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn1/HandsOn1.html">
 <span class="dropdown-text">Hands-On Exercise 1a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn1b/HandsOn1b.html">
 <span class="dropdown-text">Hands-On Exercise 1b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn2a/HandsOn2a.html">
 <span class="dropdown-text">Hands-On Exercise 2a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn2b/HandsOn2b.html">
 <span class="dropdown-text">Hands-On Exercise 2b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn3/HandsOn3.html">
 <span class="dropdown-text">Hands-On Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn4/HandsOn4.html">
 <span class="dropdown-text">Hands-On Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn5a/HandsOn5a.html">
 <span class="dropdown-text">Hands-On Exercise 5a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn5b/HandsOn5b.html">
 <span class="dropdown-text">Hands-On Exercise 5b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnExercise/HandsOn6/HandsOn6.html">
 <span class="dropdown-text">Hands-On Exercise 6</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-Class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../InClassExercise/InClass1/InClass1.html">
 <span class="dropdown-text">In-Class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../InClassExercise/InClass2/InClass2.html">
 <span class="dropdown-text">In-Class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../InClassExercise/InClass3/InClass3.html">
 <span class="dropdown-text">In-Class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../InClassExercise/InClass4/InClass4.html">
 <span class="dropdown-text">In-Class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../InClassExercise/InClass5/InClass5.html">
 <span class="dropdown-text">In-Class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../InClassExercise/InClass6/InClass6.html">
 <span class="dropdown-text">In-Class Exercise 6</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../TakeHomeExercise/TakeHome1/TakeHome1.html">
 <span class="dropdown-text">Take-Home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../TakeHomeExercise/TakeHome2/TakeHome2.html">
 <span class="dropdown-text">Take-Home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">about the author.</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#take-home-exercise-2-discovering-impacts-of-covid-19-on-thailand-tourism-economy-at-the-province-level-using-spatial-and-spatio-temporal-statistics" id="toc-take-home-exercise-2-discovering-impacts-of-covid-19-on-thailand-tourism-economy-at-the-province-level-using-spatial-and-spatio-temporal-statistics" class="nav-link active" data-scroll-target="#take-home-exercise-2-discovering-impacts-of-covid-19-on-thailand-tourism-economy-at-the-province-level-using-spatial-and-spatio-temporal-statistics"><span class="header-section-number">1</span> Take-Home Exercise 2: Discovering impacts of COVID-19 on Thailand tourism economy at the province level using spatial and spatio-temporal statistics</a>
  <ul class="collapse">
  <li><a href="#setting-the-scene" id="toc-setting-the-scene" class="nav-link" data-scroll-target="#setting-the-scene"><span class="header-section-number">1.1</span> <strong>Setting the Scene</strong></a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives"><span class="header-section-number">1.2</span> Objectives</a></li>
  <li><a href="#importing-packages" id="toc-importing-packages" class="nav-link" data-scroll-target="#importing-packages"><span class="header-section-number">1.3</span> Importing Packages</a></li>
  <li><a href="#importing-packages-1" id="toc-importing-packages-1" class="nav-link" data-scroll-target="#importing-packages-1"><span class="header-section-number">1.4</span> Importing Packages</a>
  <ul class="collapse">
  <li><a href="#importing-geopatial-data" id="toc-importing-geopatial-data" class="nav-link" data-scroll-target="#importing-geopatial-data"><span class="header-section-number">1.4.1</span> Importing Geopatial Data</a></li>
  <li><a href="#importing-aspatial-data" id="toc-importing-aspatial-data" class="nav-link" data-scroll-target="#importing-aspatial-data"><span class="header-section-number">1.4.2</span> Importing Aspatial Data</a></li>
  <li><a href="#combining-spatial-data-frame-data-frame" id="toc-combining-spatial-data-frame-data-frame" class="nav-link" data-scroll-target="#combining-spatial-data-frame-data-frame"><span class="header-section-number">1.4.3</span> Combining Spatial Data Frame &amp; Data Frame</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">1.5</span> Exploratory Data Analysis</a></li>
  <li><a href="#exploratory-spatial-data-analysis" id="toc-exploratory-spatial-data-analysis" class="nav-link" data-scroll-target="#exploratory-spatial-data-analysis"><span class="header-section-number">1.6</span> Exploratory Spatial Data Analysis</a>
  <ul class="collapse">
  <li><a href="#contiguity-based-spatial-weights" id="toc-contiguity-based-spatial-weights" class="nav-link" data-scroll-target="#contiguity-based-spatial-weights"><span class="header-section-number">1.6.1</span> Contiguity-based Spatial Weights</a></li>
  <li><a href="#distance-based-contiguity-weight-matrix" id="toc-distance-based-contiguity-weight-matrix" class="nav-link" data-scroll-target="#distance-based-contiguity-weight-matrix"><span class="header-section-number">1.6.2</span> Distance-based Contiguity Weight Matrix</a></li>
  <li><a href="#spatial-weight-matrix-to-be-employed" id="toc-spatial-weight-matrix-to-be-employed" class="nav-link" data-scroll-target="#spatial-weight-matrix-to-be-employed"><span class="header-section-number">1.6.3</span> Spatial Weight Matrix to be Employed</a></li>
  <li><a href="#row-standardised-weights-matrix" id="toc-row-standardised-weights-matrix" class="nav-link" data-scroll-target="#row-standardised-weights-matrix"><span class="header-section-number">1.6.4</span> Row-Standardised Weights Matrix</a></li>
  <li><a href="#computing-global-spatial-autocorrelation-statistics" id="toc-computing-global-spatial-autocorrelation-statistics" class="nav-link" data-scroll-target="#computing-global-spatial-autocorrelation-statistics"><span class="header-section-number">1.6.5</span> 5.1.6 Computing Global Spatial Autocorrelation Statistics</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-Home Exercise 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joshua TING </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 30, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 14, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="take-home-exercise-2-discovering-impacts-of-covid-19-on-thailand-tourism-economy-at-the-province-level-using-spatial-and-spatio-temporal-statistics" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Take-Home Exercise 2: Discovering impacts of COVID-19 on Thailand tourism economy at the province level using spatial and spatio-temporal statistics</h1>
<section id="setting-the-scene" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="setting-the-scene"><span class="header-section-number">1.1</span> <strong>Setting the Scene</strong></h2>
<p>Tourism is one of Thailand’s largest industries, accounting for some 20% of the gross domestic product (GDP). In 2019, Thailand earned 90 billion US$ from domestic and international tourism, but the COVID-19 pandemic caused revenues to crash to 24 billion US$ in 2020.</p>
<p>Figure below shows the total revenue receipt from tourism sector from January 2019 until Feb 2023. The figure reveals that the revenue from tourism industry have been recovered gradually since September 2021.</p>
</section>
<section id="objectives" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="objectives"><span class="header-section-number">1.2</span> Objectives</h2>
<p>To discover:</p>
<ul>
<li><p>if the key indicators of tourism economy of Thailand are independent from space and space and time.</p></li>
<li><p>If the tourism economy is indeed spatial and spatio-temporal dependent, then, you would like to detect where are the clusters and outliers, and the emerging hot spot/cold spot areas.</p></li>
</ul>
</section>
<section id="importing-packages" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="importing-packages"><span class="header-section-number">1.3</span> Importing Packages</h2>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, sf, spatstat, ggplot2, ggmap, tmap, dplyr, lubridate, raster, gtsummary, tidyr, spdep, knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<table class="table">
<thead>
<tr class="header">
<th>Packages</th>
<th>Function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://r-spatial.github.io/sf/"><strong>sf</strong></a></td>
<td>To import, manage, and hande geospatial data</td>
</tr>
<tr class="even">
<td><a href="https://www.tidyverse.org/"><strong>tidyverse</strong></a></td>
<td>For non-spatial data wrangling</td>
</tr>
<tr class="odd">
<td><a href="https://sfdep.josiahparry.com/"><strong>sfdep</strong></a></td>
<td>To compute spatial weights, global and local spatial autocorrelation statistics</td>
</tr>
<tr class="even">
<td><a href="https://spatstat.org/">spatstat</a></td>
<td>For analysing spatial points</td>
</tr>
<tr class="odd">
<td><a href="https://ggplot2.tidyverse.org/">ggplot2</a></td>
<td>For data divisualisation</td>
</tr>
<tr class="even">
<td><a href="https://cran.r-project.org/web/packages/ggmap/readme/README.html">ggmap</a></td>
<td>Retrieve raster map tiles from online mapping services</td>
</tr>
<tr class="odd">
<td><a href="https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html">tmap</a></td>
<td>Creating thematic maps</td>
</tr>
<tr class="even">
<td><a href="https://lubridate.tidyverse.org/">lubridate</a></td>
<td>For robust date-time usage</td>
</tr>
<tr class="odd">
<td><a href="https://rstudio.github.io/leaflet/"><strong>leaflet</strong></a></td>
<td>For interactive maps</td>
</tr>
<tr class="even">
<td><a href="https://cran.r-project.org/web/packages/knitr/"><strong>knitr</strong></a></td>
<td>For dynamic report generation</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
<table class="table">
<tbody>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="importing-packages-1" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="importing-packages-1"><span class="header-section-number">1.4</span> Importing Packages</h2>
<section id="importing-geopatial-data" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="importing-geopatial-data"><span class="header-section-number">1.4.1</span> Importing Geopatial Data</h3>
<p>In this section, <code>st_read()</code> of sf package is used to import ‘tha_adm_rtsd_itos_20210121_shp’ dataset into R enironment. <code>st_transform()</code> is used to transform the coordinate reference system (CRS) as we are assigning the boundary data for Thailand and the CRS is EPSG 32647.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>thaiboundary <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial/tha_adm_rtsd_itos_20210121_shp/"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">layer =</span> <span class="st">"tha_admbnda_adm1_rtsd_20220121"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `tha_admbnda_adm1_rtsd_20220121' from data source 
  `/Users/joshuatingsiyuan14/Desktop/isaiahting/ISSS626_GAA/TakeHomeExercise/TakeHome2/data/geospatial/tha_adm_rtsd_itos_20210121_shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 77 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>In ensuring the right assignment of the coordinate reference system to the data, <code>st_crs()</code> is used.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(thaiboundary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:32647 
  wkt:
PROJCRS["WGS 84 / UTM zone 47N",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 47N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",99,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Between 96°E and 102°E, northern hemisphere between equator and 84°N, onshore and offshore. China. Indonesia. Laos. Malaysia - West Malaysia. Mongolia. Myanmar (Burma). Russian Federation. Thailand."],
        BBOX[0,96,84,102]],
    ID["EPSG",32647]]</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(thaiboundary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 77
Columns: 17
$ Shape_Leng &lt;dbl&gt; 2.417227, 1.695100, 1.251111, 1.884945, 3.041716, 1.739908,…
$ Shape_Area &lt;dbl&gt; 0.13133873, 0.07926199, 0.05323766, 0.12698345, 0.21393797,…
$ ADM1_EN    &lt;chr&gt; "Bangkok", "Samut Prakan", "Nonthaburi", "Pathum Thani", "P…
$ ADM1_TH    &lt;chr&gt; "กรุงเทพมหานคร", "สมุทรปราการ", "นนทบุรี", "ปทุมธานี", "พระนครศรีอ…
$ ADM1_PCODE &lt;chr&gt; "TH10", "TH11", "TH12", "TH13", "TH14", "TH15", "TH16", "TH…
$ ADM1_REF   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT1EN &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT2EN &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT1TH &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT2TH &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM0_EN    &lt;chr&gt; "Thailand", "Thailand", "Thailand", "Thailand", "Thailand",…
$ ADM0_TH    &lt;chr&gt; "ประเทศไทย", "ประเทศไทย", "ประเทศไทย", "ประเทศไทย", "ประเทศ…
$ ADM0_PCODE &lt;chr&gt; "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH",…
$ date       &lt;date&gt; 2019-02-18, 2019-02-18, 2019-02-18, 2019-02-18, 2019-02-18…
$ validOn    &lt;date&gt; 2022-01-22, 2022-01-22, 2022-01-22, 2022-01-22, 2022-01-22…
$ validTo    &lt;date&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ geometry   &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((674339.8 15..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>After importing the dataset, we will plot the Thailand map using tmap.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(thaiboundary) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title =</span> <span class="st">"Thailand Administrative Boundary"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.color =</span> <span class="st">"blue"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.show =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">frame =</span> <span class="cn">FALSE</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TakeHome2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="importing-aspatial-data" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="importing-aspatial-data"><span class="header-section-number">1.4.2</span> Importing Aspatial Data</h3>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>revenue <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/thailand_domestic_tourism_2019_2023_ver2.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The data is then transposed. The “date” column is also converted to POSIXct for ease of manipulation at the later stage.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>revenue_transposed <span class="ot">&lt;-</span> revenue <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.POSIXct</span>(date)) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>province_thai, <span class="sc">-</span>region_thai) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> variable,  <span class="co"># Use unique values in 'events' as column names</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> value,  <span class="co"># Fill new columns with values from 'value'</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fill =</span> <span class="fu">list</span>(<span class="at">value =</span> <span class="dv">0</span>)  <span class="co"># Fill NA with 0</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "date"          "province_thai" "province_eng"  "region_thai"  
[5] "region_eng"    "variable"      "value"        </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
COVID-19 Pandemic in Thailand
</div>
</div>
<div class="callout-body-container callout-body">
<p>In rooting the understanding of the COVID-19 situation in Thailand, it is important to read the <a href="https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Thailand">Wiki</a> page specifically under the section of Government Response.</p>
</div>
</div>
<p>The time period of pre-COVID19 was set from 1st January 2019 to 2nd April 2020 as quoted from Wiki “<em>On 3 April, the Civil Aviation Authority of Thailand ordered that there would be a ban on all passengers flights landing in Thailand from the morning of 4 April to the evening of the 6 April..”</em> under the section of Government Response - International Travel Restrictions. Following the closure of Thailand borders on 4th April 2020, the first series of border opening was 1st July 2021 as evidenced by”<em>On 15 July 2021, it became possible for vaccinated holidaymakers from overseas to visit three islands in the Surat Thani province; Koh Samui, Koh Tao and Koh Phangan. The decision follows the reopening of Phuket, Thailand’s largest island, on Thursday, July 1</em>”. Thus, the timeframe of COVID19 was set from 4th April 2020 - 30th June 2021. The Government of Thailand only lifted the restrictions such as PCR testing for fully-vaccinated travellers on 1st May 2022 as seen “<em>Starting 1 May 2022, fully-vaccinated travellers will NOT require RT-PCR on arrival but still need Thailand Pass. ATK is voluntary only.</em>” Thus the 2nd part of COVID19 pandemic in Thailand is 1st July 2021 to 30th April 2022. 1st May 2022 marks the reopening of the country borders hence, for this post COVID19 data is set from 1st May 2022 to 31st December 2023.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>revenue_transposed <span class="ot">&lt;-</span> revenue_transposed <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Period =</span> <span class="fu">case_when</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2019-01-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2020-04-03"</span>) <span class="sc">~</span> <span class="st">"Pre-COVID"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2020-04-04"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2021-06-30"</span>) <span class="sc">~</span> <span class="st">"COVID_P1"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2021-07-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2022-04-30"</span>) <span class="sc">~</span> <span class="st">"COVID_P2"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2022-05-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-31"</span>) <span class="sc">~</span> <span class="st">"Post-COVID"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span>  <span class="co"># For any dates outside these ranges</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(revenue_transposed, <span class="st">"data/rds/revenue_transposed.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>revenue_transposed <span class="ot">=</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/revenue_transposed.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="combining-spatial-data-frame-data-frame" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="combining-spatial-data-frame-data-frame"><span class="header-section-number">1.4.3</span> Combining Spatial Data Frame &amp; Data Frame</h3>
<section id="checking-differences-in-both-sf-df" class="level4" data-number="1.4.3.1">
<h4 data-number="1.4.3.1" class="anchored" data-anchor-id="checking-differences-in-both-sf-df"><span class="header-section-number">1.4.3.1</span> Checking Differences in both SF &amp; DF</h4>
<p>Prior combining the SF &amp; DF, we would want to compare the unique values (namely the provinces) in the columns <code>"ADM1_EN"</code> from the <code>thaiboundary</code> spatial data frame and <code>"province_eng"</code> from the <code>revenue_transposed</code> data frame. The <code>unique()</code> function helps to identify any differences between the two columns.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get unique values from both columns</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>unique_thaiboundary <span class="ot">&lt;-</span> <span class="fu">unique</span>(thaiboundary<span class="sc">$</span>ADM1_EN)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>unique_revenue <span class="ot">&lt;-</span> <span class="fu">unique</span>(revenue_transposed<span class="sc">$</span>province_eng)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Find differences</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>diff_thaiboundary <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(unique_thaiboundary, unique_revenue)  <span class="co"># In thaiboundary but not in revenue</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>diff_revenue <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(unique_revenue, unique_thaiboundary)      <span class="co"># In revenue but not in thaiboundary</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame to show differences</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>difference_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">thaiboundary_only =</span> diff_thaiboundary,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">revenue_only =</span> diff_revenue</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the differences</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(difference_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  thaiboundary_only    revenue_only
1          Lop Buri         Lopburi
2          Chai Nat         Chainat
3         Chon Buri        Chonburi
4      Prachin Buri     Prachinburi
5          Buri Ram       Phang Nga
6         Si Sa Ket         Buriram
7  Nong Bua Lam Phu         Sisaket
8          Phangnga Nong Bua Lamphu</code></pre>
</div>
</div>
<p>Noticeably, we are able to witness the differences between both columns in the above output, this may result in missing values when combining both dataframes which is critical to our analysis. The differences are mainly due to the presence of white spaces.</p>
<p>Henceforth, in the below code, we update the values in the <code>"ADM1_EN"</code> column of the <code>thaiboundary</code> spatial data frame by creating a mapping of the old values to the new values and then use the <code>dplyr</code> package to perform the replacement.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame for the mapping</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mapping <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">old_value =</span> <span class="fu">c</span>(<span class="st">"Lop Buri"</span>, <span class="st">"Chai Nat"</span>, <span class="st">"Chon Buri"</span>, <span class="st">"Prachin Buri"</span>, <span class="st">"Buri Ram"</span>, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Si Sa Ket"</span>, <span class="st">"Nong Bua Lam Phu"</span>, <span class="st">"Phangnga"</span>),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">new_value =</span> <span class="fu">c</span>(<span class="st">"Lopburi"</span>, <span class="st">"Chainat"</span>, <span class="st">"Chonburi"</span>, <span class="st">"Prachinburi"</span>, <span class="st">"Buriram"</span>, </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Sisaket"</span>, <span class="st">"Nong Bua Lamphu"</span>, <span class="st">"Phang Nga"</span>),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a named vector for recoding</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>recode_vector <span class="ot">&lt;-</span> <span class="fu">setNames</span>(mapping<span class="sc">$</span>new_value, mapping<span class="sc">$</span>old_value)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Update the ADM1_EN column using recode_vector</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>thaiboundary <span class="ot">&lt;-</span> thaiboundary <span class="sc">%&gt;%</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ADM1_EN =</span> <span class="fu">recode</span>(ADM1_EN, <span class="sc">!!!</span>recode_vector))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Thereafter, we perform a check again if there are still differences between columns <code>"ADM1_EN"</code> from the <code>thaiboundary</code> spatial data frame and <code>"province_eng"</code> from the <code>revenue</code> data frame. The results returned none which is reassuring to witness.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get unique values from each column</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>unique_adm1_en <span class="ot">&lt;-</span> <span class="fu">unique</span>(thaiboundary<span class="sc">$</span>ADM1_EN)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>unique_province_eng <span class="ot">&lt;-</span> <span class="fu">unique</span>(revenue<span class="sc">$</span>province_eng)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare unique values</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>differences_adm1_en <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(unique_adm1_en, unique_province_eng)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>differences_province_eng <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(unique_province_eng, unique_adm1_en)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame to show differences side by side</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>comparison_table_check <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ADM1_EN_Not_In_Province =</span> differences_adm1_en,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">Province_Eng_Not_In_ADM1 =</span> differences_province_eng</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the comparison table</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(comparison_table_check)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: ADM1_EN_Not_In_Province &lt;chr&gt;, Province_Eng_Not_In_ADM1 &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="standardising-columns-before-joining" class="level4" data-number="1.4.3.2">
<h4 data-number="1.4.3.2" class="anchored" data-anchor-id="standardising-columns-before-joining"><span class="header-section-number">1.4.3.2</span> Standardising Columns before Joining</h4>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>thaiboundary <span class="ot">&lt;-</span> thaiboundary <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Province =</span> ADM1_EN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>revenue_transposed <span class="ot">&lt;-</span> revenue_transposed <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Province =</span> province_eng)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="combining-sf-df" class="level4" data-number="1.4.3.3">
<h4 data-number="1.4.3.3" class="anchored" data-anchor-id="combining-sf-df"><span class="header-section-number">1.4.3.3</span> Combining SF &amp; DF</h4>
<p>Unwanted columns also then removed for ease of wrangling.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>combined <span class="ot">&lt;-</span> thaiboundary <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(revenue_transposed, <span class="at">by =</span> <span class="st">"Province"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>combined <span class="ot">&lt;-</span> combined <span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>ADM1_TH, <span class="sc">-</span>ADM1_PCODE, <span class="sc">-</span>ADM1_REF, <span class="sc">-</span>ADM1ALT1EN, </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                <span class="sc">-</span>ADM1ALT2EN, <span class="sc">-</span>ADM1ALT2TH, <span class="sc">-</span>ADM0_TH,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                <span class="sc">-</span>ADM0_PCODE, <span class="sc">-</span>validTo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>basemap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(combined) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"Province"</span>, <span class="at">size=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"Period"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>rev <span class="ot">&lt;-</span> <span class="fu">qtm</span>(combined, <span class="st">"revenue_all"</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(basemap, rev, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TakeHome2_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Shape_Leng"         "Shape_Area"         "Province"          
 [4] "ADM1ALT1TH"         "ADM0_EN"            "date.x"            
 [7] "validOn"            "date.y"             "region_eng"        
[10] "ratio_tourist_stay" "no_tourist_stay"    "no_tourist_all"    
[13] "no_tourist_thai"    "no_tourist_foreign" "revenue_all"       
[16] "revenue_thai"       "revenue_foreign"    "Period"            
[19] "geometry"          </code></pre>
</div>
</div>
<p>The below code was run to simplify the gemetries through adjusting the tolerance.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>combined<span class="sc">$</span>geometry <span class="ot">&lt;-</span> <span class="fu">st_simplify</span>(combined<span class="sc">$</span>geometry, <span class="at">dTolerance =</span> <span class="fl">0.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the tmap mode to plot for static output</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">'view'</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the unique periods</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>periods <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Pre-COVID"</span>, <span class="st">"COVID_P1"</span>, <span class="st">"COVID_P2"</span>, <span class="st">"Post-COVID"</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through each period and create a map</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (period <span class="cf">in</span> periods) {</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Subset data for the current period</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  current_data <span class="ot">&lt;-</span> combined[combined<span class="sc">$</span>Period <span class="sc">==</span> period, ]</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Check if there's any data for the current period</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(current_data) <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">next</span>  <span class="co"># Skip to the next iteration if no data is found</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create the basemap</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  basemap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(current_data) <span class="sc">+</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_text</span>(<span class="st">"Province"</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="fu">paste</span>(<span class="st">"Period:"</span>, period))</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create the GDP map</span></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>  revenue <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(current_data) <span class="sc">+</span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_polygons</span>(<span class="st">"revenue_all"</span>) <span class="sc">+</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="fu">paste</span>(<span class="st">"Revenue in"</span>, period))</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Combine the basemap and GDP map</span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>  combined_map <span class="ot">&lt;-</span> <span class="fu">tmap_arrange</span>(basemap, revenue, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(combined_map)</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="map_Pre-COVID.png" class="img-fluid"></p>
<p><img src="map_COVID_P1.png" class="img-fluid"> <img src="map_COVID_P2.png" class="img-fluid"></p>
<p><img src="map_Post-COVID.png" class="img-fluid"></p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(combinedmap, <span class="st">"data/rds/combinedmap.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>combinedmap <span class="ot">=</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/combinedmap.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
</section>
<section id="exploratory-data-analysis" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="exploratory-data-analysis"><span class="header-section-number">1.5</span> Exploratory Data Analysis</h2>
<p>The code chunk below uses <em>st_area()</em> of <strong>sf</strong> package to derive the area of each province. We are creating a new column <code>Area</code> to store the area values.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>combined<span class="sc">$</span>Area <span class="ot">&lt;-</span> combined <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_area</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># input: the dataframe and the variable name, chart style, title </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>choropleth_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(rev, varname, style, title) {</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(rev) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_fill</span>(varname, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">n=</span> <span class="dv">5</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> style) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_layout</span>(<span class="at">main.title =</span> title,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">main.title.size =</span> <span class="dv">1</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">legend.height =</span> <span class="fl">0.45</span>, </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">legend.width =</span> <span class="fl">0.35</span>,</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">frame =</span> <span class="cn">TRUE</span>)<span class="sc">+</span> </span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_compass</span>(<span class="at">position =</span> <span class="fu">c</span>(<span class="st">'left'</span>,<span class="st">'bottom'</span>))</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="exploratory-spatial-data-analysis" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="exploratory-spatial-data-analysis"><span class="header-section-number">1.6</span> Exploratory Spatial Data Analysis</h2>
<section id="contiguity-based-spatial-weights" class="level3" data-number="1.6.1">
<h3 data-number="1.6.1" class="anchored" data-anchor-id="contiguity-based-spatial-weights"><span class="header-section-number">1.6.1</span> Contiguity-based Spatial Weights</h3>
<section id="contiguity-based-queen-spatial-weight-contiguity" class="level4" data-number="1.6.1.1">
<h4 data-number="1.6.1.1" class="anchored" data-anchor-id="contiguity-based-queen-spatial-weight-contiguity"><span class="header-section-number">1.6.1.1</span> <strong>Contiguity-based (Queen) Spatial Weight Contiguity</strong></h4>
<p>In the code chunk below, <a href="https://r-spatial.github.io/spdep/reference/poly2nb.html"><em>poly2nb()</em></a> of <strong>spdep</strong> package is used to compute contiguity weight matrices for the study area. This function builds a neighbours list based on regions with contiguous boundaries. By default, Queen contiguity is applied.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(thaiboundary, <span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 77 
Number of nonzero links: 352 
Percentage nonzero weights: 5.93692 
Average number of links: 4.571429 
1 region with no links:
67
2 disjoint connected subgraphs
Link number distribution:

 0  1  2  3  4  5  6  7  8  9 
 1  1  5 17 15 17 10  5  4  2 
1 least connected region:
14 with 1 link
2 most connected regions:
29 51 with 9 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 77 area units in Thailand. The most connected area unit has 9 links.</p>
</section>
<section id="contiguity-based-rook-spatial-weight-contiguity" class="level4" data-number="1.6.1.2">
<h4 data-number="1.6.1.2" class="anchored" data-anchor-id="contiguity-based-rook-spatial-weight-contiguity"><span class="header-section-number">1.6.1.2</span> <strong>Contiguity-based (Rook) Spatial Weight Contiguity</strong></h4>
<p>In the code chunk below, <a href="https://r-spatial.github.io/spdep/reference/poly2nb.html"><em>poly2nb()</em></a> of <strong>spdep</strong> package is used to compute contiguity weight matrices for the study area. We specify <code>queen = FALSE</code> to compute Rook contiguity.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(thaiboundary, <span class="at">queen=</span><span class="cn">FALSE</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 77 
Number of nonzero links: 352 
Percentage nonzero weights: 5.93692 
Average number of links: 4.571429 
1 region with no links:
67
2 disjoint connected subgraphs
Link number distribution:

 0  1  2  3  4  5  6  7  8  9 
 1  1  5 17 15 17 10  5  4  2 
1 least connected region:
14 with 1 link
2 most connected regions:
29 51 with 9 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 77 area units in Thailand. The most connected area unit has 9 links.</p>
<p>Both of them possess the same number of link (4.57).</p>
</section>
</section>
<section id="distance-based-contiguity-weight-matrix" class="level3" data-number="1.6.2">
<h3 data-number="1.6.2" class="anchored" data-anchor-id="distance-based-contiguity-weight-matrix"><span class="header-section-number">1.6.2</span> Distance-based Contiguity Weight Matrix</h3>
<p>We will derive the distance-based weight matrices by using <a href="https://r-spatial.github.io/spdep/reference/dnearneigh.html"><em>dnearneigh()</em></a> of <strong>spdep</strong> package. The function identifies neighbours of region points by Euclidean distance with a distance band with lower and upper bounds controlled by the <em>bounds</em> argument or by Great Circle distance in kilometres if <em>longlat</em> argument is set to TRUE.</p>
<section id="fixed-distance-weight-matrix" class="level4" data-number="1.6.2.1">
<h4 data-number="1.6.2.1" class="anchored" data-anchor-id="fixed-distance-weight-matrix"><span class="header-section-number">1.6.2.1</span> <strong>Fixed Distance Weight Matrix</strong></h4>
<p><strong>Determining the cut-off distance</strong></p>
<p>To ensure that each region has at least one neighbour, we need to find out the minimum distance within which all regions have at least oneneighbour. We can do this by following these steps:</p>
<ul>
<li><p>Getting the coordinates of polygon centroids. This is required as an input in the next step.</p>
<p>We need to associate each polygon with a point and its coordinates need to be in a separate data frame. We will use a mapping function that applies a given function to each element of a vector and returns a vector of the same length. Our input vector will be the geometry column of <code>thaiboundary</code>. Our function will be <em>st_centroid()</em>. We will be using <em>map_dbl()</em> variation of <a href="https://www.rdocumentation.org/packages/purrr/versions/0.2.5/topics/map">map</a> from the <strong>purrr</strong> package. <strong>purrr</strong> is loaded when we load <strong>tidyverse</strong> package.</p></li>
<li><p>To get our longitude values we map the <em>st_centroid()</em> function over the geometry column of thaiboundary and access the longitude value through double bracket notation [[]] and</p>
<ol type="1">
<li>This allows us to get only the longitude, which is the first value in each centroid.</li>
</ol></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(thaiboundary<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We do the same for latitude with one key difference. We access the second value per each centroid with [[2]]</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(thaiboundary<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now that we have latitude and longitude, I used cbind to put longitude and latitude into the same object. We should check the first few observations to see if things are formatted correctly.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude latitude
[1,]  675514.6  1523087
[2,]  685033.7  1503755
[3,]  650477.2  1539777
[4,]  681656.0  1555581
[5,]  664627.1  1586462</code></pre>
</div>
</div>
<ul>
<li><p>Return a matrix with the indices of points belonging to the set of the k nearest neighbours of each other by using <a href="https://r-spatial.github.io/spdep/reference/knearneigh.html"><em>knearneigh()</em></a> of <strong>spdep.</strong></p></li>
<li><p>Convert the knn object returned by <em>knearneigh()</em> into a neighbours list of class nb with a list of integer vectors containing neighbour region number ids by using <a href="https://r-spatial.github.io/spdep/reference/knn2nb.html"><em>knn2nb()</em></a>.</p></li>
<li><p>Return the length of neighbour relationship edges by using <a href="https://r-spatial.github.io/spdep/reference/nbdists.html"><em>nbdists()</em></a> of <strong>spdep</strong>. The function returns in the units of the coordinates if the coordinates are projected, in km otherwise.</p></li>
<li><p>Remove the list structure of the returned object by using <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/unlist">unlist()</a>.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>k1 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k =</span> <span class="dv">1</span>))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>k1dists <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">nbdists</span>(k1, coords))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(k1dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  21548   51966   64530   63281   76823  110987 </code></pre>
</div>
</div>
<p>The summary report shows that the largest first nearest neighbour distance is 110,987 metres, approximately 111, 000 metres. This will be used as the upper threshold as it gives certainty that all regions will have at least one neighbour.</p>
<p><strong>Computing the fixed distance weight matrix</strong></p>
<p>Now, we will compute the distance weight matrix by using <a href="https://r-spatial.github.io/spdep/reference/dnearneigh.html"><em>dnearneigh()</em></a> as shown below.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>wm_d111 <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords,<span class="dv">0</span>,<span class="dv">111000</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>wm_d111</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 77 
Number of nonzero links: 350 
Percentage nonzero weights: 5.903188 
Average number of links: 4.545455 
2 disjoint connected subgraphs</code></pre>
</div>
</div>
<p>From the above code, we can see that the average number of links is 4.54.</p>
<p>Next, we use <em>str()</em> to display the content of <code>wm_d111</code> weight matrix.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wm_d111)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>List of 77
 $ : int [1:12] 2 3 4 5 6 10 11 15 17 59 ...
 $ : int [1:10] 1 3 4 5 11 15 17 59 60 61
 $ : int [1:13] 1 2 4 5 6 8 10 17 56 58 ...
 $ : int [1:14] 1 2 3 5 6 8 10 15 16 17 ...
 $ : int [1:13] 1 2 3 4 6 7 8 9 10 17 ...
 $ : int [1:11] 1 3 4 5 7 8 9 10 17 58 ...
 $ : int [1:7] 5 6 8 9 10 17 48
 $ : int [1:10] 3 4 5 6 7 9 10 48 49 58
 $ : int [1:7] 5 6 7 8 48 49 58
 $ : int [1:9] 1 3 4 5 6 7 8 16 17
 $ : int [1:6] 1 2 12 13 15 16
 $ : int [1:3] 11 13 15
 $ : int [1:5] 11 12 14 15 18
 $ : int 13
 $ : int [1:9] 1 2 4 11 12 13 16 17 18
 $ : int [1:6] 4 10 11 15 17 18
 $ : int [1:10] 1 2 3 4 5 6 7 10 15 16
 $ : int [1:3] 13 15 16
 $ : int 20
 $ : int [1:2] 19 21
 $ : int [1:2] 20 22
 $ : int [1:2] 21 23
 $ : int [1:2] 22 26
 $ : int [1:3] 26 34 38
 $ : int [1:2] 29 55
 $ : int [1:4] 23 24 34 38
 $ : int [1:2] 32 36
 $ : int [1:4] 29 30 31 32
 $ : int [1:3] 25 28 33
 $ : int [1:3] 28 32 36
 $ : int 28
 $ : int [1:3] 27 28 30
 $ : int [1:3] 29 34 35
 $ : int [1:5] 24 26 33 35 38
 $ : int [1:4] 33 34 36 38
 $ : int [1:4] 27 30 35 37
 $ : int [1:2] 36 38
 $ : int [1:5] 24 26 34 35 37
 $ : int [1:3] 40 41 47
 $ : int [1:2] 39 41
 $ : int [1:3] 39 40 43
 $ : int [1:3] 43 52 53
 $ : int [1:4] 41 42 44 52
 $ : int [1:2] 43 45
 $ : int [1:2] 44 46
 $ : int 45
 $ : int 39
 $ : int [1:6] 7 8 9 49 50 54
 $ : int [1:6] 8 9 48 50 57 58
 $ : int [1:5] 48 49 51 52 54
 $ : int 50
 $ : int [1:4] 42 43 50 53
 $ : int [1:4] 42 52 54 55
 $ : int [1:4] 48 50 53 55
 $ : int [1:3] 25 53 54
 $ : int [1:5] 3 59 60 61 62
 $ : int [1:2] 49 58
 $ : int [1:9] 3 4 5 6 8 9 49 57 59
 $ : int [1:10] 1 2 3 4 5 6 56 58 60 61
 $ : int [1:9] 1 2 3 4 5 56 59 61 62
 $ : int [1:8] 1 2 3 4 56 59 60 62
 $ : int [1:4] 56 60 61 63
 $ : int 62
 $ : int [1:4] 65 68 73 74
 $ : int [1:5] 64 66 67 68 73
 $ : int [1:3] 65 67 68
 $ : int [1:2] 65 66
 $ : int [1:4] 64 65 66 69
 $ : int [1:2] 68 70
 $ : int 69
 $ : int [1:3] 72 74 75
 $ : int [1:3] 71 73 74
 $ : int [1:4] 64 65 72 74
 $ : int [1:4] 64 71 72 73
 $ : int [1:3] 71 76 77
 $ : int [1:2] 75 77
 $ : int [1:2] 75 76
 - attr(*, "class")= chr "nb"
 - attr(*, "region.id")= chr [1:77] "1" "2" "3" "4" ...
 - attr(*, "call")= language dnearneigh(x = coords, d1 = 0, d2 = 111000)
 - attr(*, "dnn")= num [1:2] 0 111000
 - attr(*, "bounds")= chr [1:2] "GE" "LE"
 - attr(*, "nbtype")= chr "distance"
 - attr(*, "sym")= logi TRUE</code></pre>
</div>
</div>
<p>We can observe that each region has different number of neighbours.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thaiboundary<span class="sc">$</span>geometry, <span class="at">border =</span> <span class="st">"lightgrey"</span>,<span class="at">main=</span><span class="st">"1st nearest neighbours"</span> )</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">length =</span> <span class="fl">0.88</span>, )</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thaiboundary<span class="sc">$</span>geometry, <span class="at">border =</span> <span class="st">"lightgrey"</span>, <span class="at">main =</span> <span class="st">"Distance Link"</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d111, coords, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TakeHome2_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the above output, we can make a few observations:</p>
<ul>
<li><p>It illustrates a characteristic of fixed distance weight matrix–more densely settled areas (usually the urban areas) tend to have more neighbours which is in instance it is in the middle where Bangkok resides and the less densely settled areas (usually the rural provinces) tend to have lesser neighbours</p></li>
<li><p>The geographical areas of the regions in Thailand are largely varying. In the middle, bottom and top right, we see the neighbour links are dense especially in the middle and less dense in the rest of the regions where white spaces are</p></li>
<li><p>Lastly, it is interesting to note that there is a dead space between the densely settled area of Bangkok region and the southern part of Thailand. This may indicate that tourism was not developed at all.</p></li>
</ul>
</section>
<section id="adaptive-distance-based-weight-matrix" class="level4" data-number="1.6.2.2">
<h4 data-number="1.6.2.2" class="anchored" data-anchor-id="adaptive-distance-based-weight-matrix"><span class="header-section-number">1.6.2.2</span> <strong>Adaptive Distance-based Weight Matrix</strong></h4>
<p>To overcome the issue of fixed distance weight matrix where there is uneven distribution of neighbours, we can use directly control the numbers of neighbours using k-nearest neighbours, as shown in the code chunk below.</p>
<p>As a rule-of-thumb, we will set k = 8 i.e., all regions will have 8 neighbours.</p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>knn8 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">8</span>))</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>knn8</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 77 
Number of nonzero links: 616 
Percentage nonzero weights: 10.38961 
Average number of links: 8 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<p><strong>Plotting Adaptive Distance-based Neighbours</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thaiboundary<span class="sc">$</span>geometry, <span class="at">border =</span> <span class="st">"lightgrey"</span>,<span class="at">main=</span><span class="st">"8 nearest neighbours"</span> )</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(knn8, coords, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">length =</span> <span class="fl">0.88</span>, )</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thaiboundary<span class="sc">$</span>geometry, <span class="at">border =</span> <span class="st">"lightgrey"</span>, <span class="at">main =</span> <span class="st">"Distance Link w KNN"</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(knn8, coords, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TakeHome2_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="spatial-weight-matrix-to-be-employed" class="level3" data-number="1.6.3">
<h3 data-number="1.6.3" class="anchored" data-anchor-id="spatial-weight-matrix-to-be-employed"><span class="header-section-number">1.6.3</span> Spatial Weight Matrix to be Employed</h3>
<p>Selecting a spatial weight matrix is use is dependent on the geographical area of interest and the focus of the study<sup><a href="https://isss624-amelia.netlify.app/exercises/take-home_ex1/take-home_ex1#fn8">8</a></sup>.</p>
<p>In this study, between contiguity-based and distance-based spatial weight matrices, we lean towards distance-based matrices. Within distance-based matrices, we will select the adaptive distance-based spatial weight matrix for our subsequent analysis.</p>
<p>The reasons are summarised here:</p>
<ul>
<li><p>Thailand has 77 provinces and it is relatively small . Hence, a contiguity-based matrix will have the issue where larger LGAs have more neighbours and smaller LGAs have lesser neighbours. This would likely skew our analysis. Therefore, distance-based methods are preferred.</p></li>
<li><p>As mentioned earlier, the fixed distance-based method has the disadvantage that some regions would only have 1 neighbour, while on average regions have 23 neighbours. Statistical test for regions with only 1 neighbour may not be valid.</p></li>
</ul>
<p>Based on the above, we will select adaptive distance-based spatial weight matrix.</p>
</section>
<section id="row-standardised-weights-matrix" class="level3" data-number="1.6.4">
<h3 data-number="1.6.4" class="anchored" data-anchor-id="row-standardised-weights-matrix"><span class="header-section-number">1.6.4</span> Row-Standardised Weights Matrix</h3>
<div class="cell">
<details class="code-fold">
<summary>Code Chunk</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>rswm_knn8 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn8,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">style =</span> <span class="st">"W"</span>,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>rswm_knn8</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 77 
Number of nonzero links: 616 
Percentage nonzero weights: 10.38961 
Average number of links: 8 
Non-symmetric neighbours list

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 77 5929 77 17.03125 319.9688</code></pre>
</div>
</div>
<p>We will be using the row-standardised weight matrix for the next part of the analysis.</p>
</section>
<section id="computing-global-spatial-autocorrelation-statistics" class="level3" data-number="1.6.5">
<h3 data-number="1.6.5" class="anchored" data-anchor-id="computing-global-spatial-autocorrelation-statistics"><span class="header-section-number">1.6.5</span> 5.1.6 Computing Global Spatial Autocorrelation Statistics</h3>
<p>This in sub-section, we will use two methods: Moran’s I and Geary’s C to test the hypothesis the following hypothesis:</p>
<ul>
<li><p>H0: Observed spatial patterns of values is equally likely as any other spatial pattern i.e.&nbsp;data is randomly disbursed, no spatial pattern</p></li>
<li><p>H1: Data is more spatially clustered than expected by chance alone.</p></li>
</ul>
<section id="morans-i" class="level4" data-number="1.6.5.1">
<h4 data-number="1.6.5.1" class="anchored" data-anchor-id="morans-i"><span class="header-section-number">1.6.5.1</span> 5.1.6.1 Moran’s I</h4>
<p>We will perform Moran’s I statistical testing by using <a href="https://r-spatial.github.io/spdep/reference/moran.test.html"><em>moran.test()</em></a> of <strong>spdep</strong>. Moran’s I describe how features differ from the values in the study area as a whole. The Moran I statistic ranges from -1 to 1. If the Moran I is:</p>
<ul>
<li><p>positive (I&gt;0): Clustered, observations tend to be similar</p></li>
<li><p>negative (I&lt;0): Disperse, observations tend to be dissimilar</p></li>
<li><p>approximately zero: observations arranged randomly over space</p></li>
</ul>
<p>The below code chunk will perform the Moran’s I test on both functional and non-functional water points.</p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>